// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "greenbox",
    "version": "1"
  },
  "paths": {
    "/": {
      "get": {
        "summary": "healthcheck",
        "description": "",
        "operationId": "healthcheck.get./",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/login": {
      "get": {
        "summary": "login",
        "description": "",
        "operationId": "login.get./login",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/ftlogin": {
      "get": {
        "summary": "ftlogin",
        "description": "",
        "operationId": "ftlogin.get./ftlogin",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/ftlogin/return": {
      "get": {
        "summary": "return",
        "description": "",
        "operationId": "return.get./ftlogin/return",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/item": {
      "get": {
        "summary": "item",
        "description": "",
        "operationId": "item.get./item",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/user": {
      "get": {
        "summary": "user",
        "description": "",
        "operationId": "user.get./user",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/user/me": {
      "get": {
        "summary": "user",
        "description": "",
        "operationId": "user.get./user/me",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/storage": {
      "get": {
        "summary": "storage",
        "description": "",
        "operationId": "storage.get./storage",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "post": {
        "summary": "storage",
        "description": "",
        "operationId": "storage.post./storage",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/storage/me": {
      "get": {
        "summary": "storage",
        "description": "",
        "operationId": "storage.get./storage/me",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/ledger": {
      "get": {
        "summary": "ledger",
        "description": "",
        "operationId": "ledger.get./ledger",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {}
};